### ISSUE TITLE
Improvements for onSuccess/onFailure behaviour

### ISSUE THREAD

**Issue by matbrat** [a-sit-plus/KmmResult#6]
In Kotlin, Result class have this structure for `onSuccess` and `onFailure` method:

```kotlin
@InlineOnly
@SinceKotlin("1.3")
public inline fun <T> Result<T>.onSuccess(action: (value: T) -> Unit): Result<T> {
    contract {
        callsInPlace(action, InvocationKind.AT_MOST_ONCE)
    }
    if (isSuccess) action(value as T)
    return this
}
@InlineOnly
@SinceKotlin("1.3")
public inline fun <T> Result<T>.onFailure(action: (exception: Throwable) -> Unit): Result<T> {
    contract {
        callsInPlace(action, InvocationKind.AT_MOST_ONCE)
    }
    exceptionOrNull()?.let { action(it) }
    return this
}
```

Methods returns Result object:

KmmResult have different behaviour.

```kotlin
    /**
     * singular version of `fold`'s `onSuccess`
     */
    inline fun <R> onSuccess(block: (value: T) -> R) {
        getOrNull()?.let { block(it) }
    }

    /**
     * singular version of `fold`'s `onFailure`
     */
    inline fun <R> onFailure(block: (error: Throwable) -> R) {
        exceptionOrNull()?.let { block(it) }
    }
 ```
 
 Is it possible to adjust KmmResult code to have similar behaviours as original Kotlin Result?

**Comment by JesusMcCloud** [comment]
Happy? https://github.com/a-sit-plus/KmmResult/blob/12bd661c7c6ec40a2cb8946567db958e8d19a8d6/src/commonMain/kotlin/at/asitplus/KmmResult.kt#L194
https://github.com/a-sit-plus/KmmResult/blob/12bd661c7c6ec40a2cb8946567db958e8d19a8d6/src/commonMain/kotlin/at/asitplus/KmmResult.kt#L205

**Comment by JesusMcCloud** [comment]
part of 1.7.0, which is currently being released to maven central
