### ISSUE TITLE
Kotest extensions

### ISSUE THREAD

**Issue by iaik-jheher** [a-sit-plus/KmmResult#7]
We have `KmmResult` extension functions for Kotest over in kmp-crypto: for example [here](https://github.com/a-sit-plus/kmp-crypto/blob/f348447a9cb4a0b83caa777d15ee4a9b80103e1f/datatypes/src/jvmTest/kotlin/at/asitplus/crypto/datatypes/X509ConversionTests.kt#L8) and [here](https://github.com/a-sit-plus/kmp-crypto/blob/f348447a9cb4a0b83caa777d15ee4a9b80103e1f/provider/src/commonTest/kotlin/at/asitplus/crypto/provider/TestUtils.kt#L9).

These are generally useful and should be part of KmmResult proper.

**Comment by JesusMcCloud** [comment]
fixed with #9
