### ISSUE TITLE
Xcode 16 / Swift 6 support?

### ISSUE THREAD

**Issue by mandrachek** [a-sit-plus/KmmResult#8]
I'm using KmmResult in a KMP library project.  I just upgraded to XCode 16 along with Sequoia, and so got upgraded to Swift 6.  

My KmmResult stopped working on iOS - the .fold {} never was entered, similar results with .onSuccess{}.onFailure{}.getOrNull() - the methods appear to never get called.

I've done a build with a Swift 5.10.1 toolchain.  I'll report back if that build works.  But it appears there may be some Swift 6 incompatibilities - not sure if it's in KmmResult, or KMP in general.

**Comment by JesusMcCloud** [comment]
Thank you for reporting and investigating this!

**Comment by mandrachek** [comment]
This is not, from what I can tell, a KmmResult issue.  It's more likely an SKIE issue.  Thanks!
